services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pregnacare-api
    restart: always
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node-modules/
        - action: rebuild
          path: package.json
    ports:
      - '8080:8080'
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    depends_on:
      - mongo
      - cache
    env_file: .env.development
  mongo:
    image: mongo
    container_name: pregnacare-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
  cache:
    image: redis:6.2-alpine
    container_name: pregnacare-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis_data:/data/db

  cache_commander:
    platform: linux/amd64
    container_name: pregnacare-cache-commander
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - '8081:8081'
    depends_on:
      - cache

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
